version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: nexus_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: company_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stoppedthe design of landingpage is totally different forn the the this one make this one similar to that one and yes the header and footer are also not correct what ever frontend idea i gave implemnt that to the whole project

  redis:
    image: redis:7-alpine
    container_name: nexus_cache
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
